version: '{build}'
image: Visual Studio 2019
clone_depth: 50

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet build ./src/Plaid/Plaid.csproj -c Release

after_test:
    - cmd: dotnet pack ./src/Plaid/Plaid.csproj -c Release

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

deploy:
 -  provider: NuGet
    api_key:
        secure: PXXLxEGnQq6BGX+BDU+ll6IJplwZ3MdiSyGM2VTtP67ru2QvCyBXACs68quskxGo
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on: 
        APPVEYOR_REPO_TAG: true        # deploy on tag push only

 -  provider: GitHub
    auth_token:
        secure: gLjuy01aV234sOjDtHTsqYPwox1c1Qj6uHYSIg0ToLcBDdbGePs30M6Dx/fmFdyX
    name: Release $(APPVEYOR_REPO_TAG_NAME)
    description: Release $(APPVEYOR_REPO_TAG_NAME)
    artifact: /.*(\.|\.s)nupkg/
    on: 
        APPVEYOR_REPO_TAG: true        # deploy on tag push only
